In [330]:
import pandas as pd
import numpy as np

In [331]:
data = pd.read_csv("PersonalFinancesUpdated.csv")

In [332]:
data.head()

,Unnamed: 0,Food,Unnamed: 2,Other Things,Unnamed: 4,Subscriptions,Unnamed: 6,lege/strom/vand,Transport,Hygge,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total,253068.0,0,344123,0,43117,NaN,157318.0,30020.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20-02-2025,NaN,NaN,2808,Unitop,NaN,NaN,9500.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [333]:
data.describe()

,Food,lege/strom/vand,Transport,Hygge,Family,Unnamed: 12,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
count,755.000000,40.000000,84.000000,1.0,138.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,670.378808,8103.400000,714.761905,0.0,2212.855072,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,9208.547938,25106.714884,3303.428021,NaN,12989.083509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,10.000000,0.000000,20.000000,0.0,10.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,78.500000,890.250000,60.000000,0.0,103.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,180.000000,1903.000000,200.000000,0.0,500.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,420.000000,4114.000000,305.750000,0.0,1507.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,253068.000000,157318.000000,30020.000000,0.0,152687.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [334]:
data.columns = data.columns.str.strip().str.lower().str.replace(" ", "_").str.replace(r'[^\w]', '', regex=True)

In [335]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   unnamed_0      406 non-null    object
 1   food           755 non-null    float64
 2   unnamed_2      755 non-null    object
 3   other_things   234 non-null    object
 4   unnamed_4      233 non-null    object
 5   subscriptions  47 non-null     object
 6   unnamed_6      45 non-null     object
 7   legestromvand  40 non-null     float64
 8   transport      84 non-null     float64
 9   hygge          1 non-null      float64
 10  family         138 non-null    float64
 11  unnamed_11     138 non-null    object
 12  unnamed_12     1 non-null      float64
 13  unnamed_13     2 non-null      object
 14  unnamed_14     1 non-null      float64
 15  unnamed_15     1 non-null      float64
 16  unnamed_16     1 non-null      float64
 17  unnamed_17     1 non-null      float64
 18  unnamed_18     1 non-null      float64
 19  unnamed_19     1 non-null      float64
 20  unnamed_20     1 non-null      float64
 21  unnamed_21     1 non-null      float64
 22  unnamed_22     1 non-null      float64
 23  unnamed_23     1 non-null      float64
 24  unnamed_24     1 non-null      float64
 25  unnamed_25     1 non-null      float64
 26  unnamed_26     1 non-null      float64
dtypes: float64(19), object(8)
memory usage: 202.2+ KB

In [336]:
data.columns

Index(['unnamed_0', 'food', 'unnamed_2', 'other_things', 'unnamed_4',
       'subscriptions', 'unnamed_6', 'legestromvand', 'transport', 'hygge',
       'family', 'unnamed_11', 'unnamed_12', 'unnamed_13', 'unnamed_14',
       'unnamed_15', 'unnamed_16', 'unnamed_17', 'unnamed_18', 'unnamed_19',
       'unnamed_20', 'unnamed_21', 'unnamed_22', 'unnamed_23', 'unnamed_24',
       'unnamed_25', 'unnamed_26'],
      dtype='object')

In [337]:
data = data.drop(columns=['hygge', 'unnamed_12', 'unnamed_13', 'unnamed_14',
       'unnamed_15', 'unnamed_16', 'unnamed_17', 'unnamed_18', 'unnamed_19',
       'unnamed_20', 'unnamed_21', 'unnamed_22', 'unnamed_23', 'unnamed_24',
       'unnamed_25', 'unnamed_26'])

In [338]:
data.rename(columns={
    'unnamed_0': "date",
     "unnamed_2": "food_type",
    "unnamed_4": "other_things_type",
    "unnamed_6": "subscriptions_type",
    "legestromvand": "housing_utilities",
    "unnamed_11": "family_type"
    }, inplace=True)

In [339]:
data= data.drop(data.index[1])
data = data.dropna(axis=0, how="all")
data.head()

,date,food,food_type,other_things,other_things_type,subscriptions,subscriptions_type,housing_utilities,transport,family,family_type
4,20-02-2025,NaN,NaN,2808,Unitop,NaN,NaN,9500.0,NaN,NaN,NaN
5,28-02-2025,200.0,Coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,359.0,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,01-03-2025,1485.0,SM Supermarket,200,Slippers Ivy,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,80.0,sugar drinks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [340]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 936 entries, 4 to 957
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                405 non-null    object
 1   food                754 non-null    float64
 2   food_type           754 non-null    object
 3   other_things        233 non-null    object
 4   other_things_type   232 non-null    object
 5   subscriptions       46 non-null     object
 6   subscriptions_type  45 non-null     object
 7   housing_utilities   39 non-null     float64
 8   transport           83 non-null     float64
 9   family              137 non-null    float64
 10  family_type         137 non-null    object
dtypes: float64(4), object(7)
memory usage: 87.8+ KB

In [341]:
#Convert the date column into datetime format
data["date"] = pd.to_datetime(data["date"], errors="coerce")

C:\Users\marcu\AppData\Local\Temp\ipykernel_17184\2942820378.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data["date"] = pd.to_datetime(data["date"], errors="coerce")

In [342]:
#The columns "other_things" and "subscriptions" should be Dtype = float64

In [343]:
data["other_things"].apply(type).value_counts()

other_things
<class 'float'>    703
<class 'str'>      233
Name: count, dtype: int64

In [344]:
data["subscriptions"].apply(type).value_counts()

subscriptions
<class 'float'>    890
<class 'str'>       46
Name: count, dtype: int64

In [345]:
import re

In [346]:
outlier_rows = data[data["other_things"].apply(
    lambda x: isinstance(x, str) and not re.fullmatch(r"^\d+(\.\d+)?$", x)
)]
print(outlier_rows)

          date  food food_type other_things other_things_type subscriptions  \
131 2025-05-01  90.0       NaN        Mango               NaN           NaN

    subscriptions_type  housing_utilities  transport  family family_type
131                NaN                NaN        NaN     NaN         NaN

In [347]:

row_idx = 131
data.loc[row_idx, "food_type"] = data.loc[row_idx, "other_things"]
data.loc[row_idx, "other_things"] = pd.NA

In [348]:
outlier_rows = data[data["other_things"].apply(
    lambda x: isinstance(x, str) and not re.fullmatch(r"^\d+(\.\d+)?$", x)
)]
print(outlier_rows)

Empty DataFrame
Columns: [date, food, food_type, other_things, other_things_type, subscriptions, subscriptions_type, housing_utilities, transport, family, family_type]
Index: []

In [349]:
outlier_rows = data[data["subscriptions"].apply(
    lambda x: isinstance(x, str) and not re.fullmatch(r"^\d+(\.\d+)?$", x)
)]
print(outlier_rows)

          date  food      food_type other_things other_things_type  \
158 2025-05-16  90.0  Street Store           NaN               NaN

    subscriptions subscriptions_type  housing_utilities  transport  family  \
158  10 piso wifi                NaN                NaN        NaN     NaN

    family_type
158         NaN

In [350]:
data.loc[158, "subscriptions"] = "10"
data.loc[158, "subscriptions_type"] = "piso wifi"

In [351]:
outlier_rows = data[data["subscriptions"].apply(
    lambda x: isinstance(x, str) and not re.fullmatch(r"^\d+(\.\d+)?$", x)
)]
print(outlier_rows)

Empty DataFrame
Columns: [date, food, food_type, other_things, other_things_type, subscriptions, subscriptions_type, housing_utilities, transport, family, family_type]
Index: []

In [352]:
#We can safely convert the column other_things and subscriptions into numeric.
data["other_things"] = pd.to_numeric(data["other_things"], errors="coerce")
data["subscriptions"] = pd.to_numeric(data["subscriptions"], errors="coerce")

In [353]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 936 entries, 4 to 957
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                405 non-null    datetime64[ns]
 1   food                754 non-null    float64
 2   food_type           755 non-null    object
 3   other_things        232 non-null    float64
 4   other_things_type   232 non-null    object
 5   subscriptions       46 non-null     float64
 6   subscriptions_type  46 non-null     object
 7   housing_utilities   39 non-null     float64
 8   transport           83 non-null     float64
 9   family              137 non-null    float64
 10  family_type         137 non-null    object
dtypes: datetime64[ns](1), float64(6), object(4)
memory usage: 120.0+ KB

In [354]:
#Clean the cells - Empty spaces, all lower cases 
type_columns = ["food_type", "other_things_type", "subscriptions_type", "family_type"]

for col in type_columns:
    data[col] = data[col].str.strip().str.lower().str.replace(" ", "_").str.replace(r'[^\w]', '', regex=True)

In [355]:
#Lets model the data into 4 columns: Date, Category, Amount, Detail
detailed = {
    "food": "food_type",
    "subscriptions": "subscriptions_type",
    "other_things": "other_things_type",
    "family": "family_type"
}
simple = [
    "transport",
    "housing_utilities"
]

tidy_rows = []

for amount_col, detail_col in detailed.items():
    temp = data[["date", amount_col, detail_col]].copy()
    temp = temp.rename(columns={
        amount_col: "amount",
        detail_col: "detail"
    })
    temp["category"] = amount_col
    tidy_rows.append(temp)


for amount_col in simple:
    temp = data[["date", amount_col]].copy()
    temp = temp.rename(columns={amount_col: "amount"})
    temp["detail"] = None
    temp["category"] = amount_col
    tidy_rows.append(temp)

tidy = pd.concat(tidy_rows, ignore_index=True)

#Delete empty rows
tidy = tidy.dropna(subset=['amount'])
tidy = tidy[tidy['amount'] > 0]

In [356]:
tidy.head()

        date  amount          detail category
1 2025-02-28   200.0          coffee     food
2        NaT   359.0       mcdonalds     food
3 2025-03-01  1485.0  sm_supermarket     food
4        NaT    80.0    sugar_drinks     food
5        NaT    45.0          unitop     food

In [357]:
tidy["date"] = tidy["date"].ffill()

In [358]:
tidy.head()

        date  amount          detail category
1 2025-02-28   200.0          coffee     food
2 2025-02-28   359.0       mcdonalds     food
3 2025-03-01  1485.0  sm_supermarket     food
4 2025-03-01    80.0    sugar_drinks     food
5 2025-03-01    45.0          unitop     food

In [359]:
# Count how many times each variant appears
counts = tidy["detail"].value_counts(dropna=True)
print(counts)

detail
street_store      93
bakery            83
mcdonalds         50
sm_supermarket    47
sugar_drinks      37
                  ..
nokia_nanay        1
gloves             1
worker_jaime       1
worker_ludito      1
tatay_sander       1
Name: count, Length: 270, dtype: int64

In [360]:
#Lets see how many variables belong to each category
counts_detail_category = tidy.groupby(['category', 'detail']).size().sort_values(ascending=False)
counts_detail_category = counts_detail_category.reset_index(name='count')

print(counts_detail_category.head(30))

         category              detail  count
0            food        street_store     86
1            food              bakery     80
2            food           mcdonalds     50
3            food      sm_supermarket     47
4            food        sugar_drinks     37
5            food   restaurant_taytay     27
6            food          vegetables     27
7            food               water     25
8            food              coffee     24
9            food             chicken     21
10   other_things              shopee     17
11   other_things           drugstore     16
12   other_things           gcash_fee     16
13           food          tokyotokyo     16
14           food            icecream     15
15           food       seattles_best     15
16           food                eggs     15
17           food                fish     14
18           food            halohalo     14
19           food         street_food     13
20  subscriptions                 gym     12
21   other_things             pigfood     12
22         family                kids     11
23           food            chowking     11
24           food              banana     11
25           food         supermarket     11
26           food  shopee_supermarket     10
27  subscriptions        load_tnt_sim     10
28           food            ribshack     10
29           food    nccc_supermarket      9

In [361]:
mapping = {

# ======================
# EATING OUT / RESTAURANTS
# ======================
'mcdonalds': 'restaurants','tokyotokyo': 'restaurants','ribshack': 'restaurants','chowking': 'restaurants','kfc': 'restaurants',
'popeyes': 'restaurants','jollibee': 'restaurants','greenwich': 'restaurants','subway': 'restaurants','taco_bell': 'restaurants',
'shakeys_pizza': 'restaurants','burger_king': 'restaurants','saigosan': 'restaurants','inasal': 'restaurants','halohalo': 'restaurants',
'restaurant_taytay': 'restaurants','restaurant_puertoprincesa': 'restaurants','restaurant_chillis': 'restaurants','buffet': 'restaurants',
'seattles_best': 'restaurants','street_food': 'restaurants','friend_food': 'restaurants','kaptains_diner': 'restaurants',
'shawarma': 'restaurants','pedros_silog': 'restaurants','foodpanda': 'restaurants','restaurant': 'restaurants','ramen': 'restaurants',
# ======================
# SNACKS & DRINKS
# ======================
'coffee': 'snacks_drinks','coffee_shop': 'snacks_drinks','coffee_shop_taytay': 'snacks_drinks','mcdonalds_caffe': 'snacks_drinks',
'icecream': 'snacks_drinks','sugar_drinks': 'snacks_drinks','2sugar_drinks': 'snacks_drinks','sugar_drink': 'snacks_drinks',
'cocacola': 'snacks_drinks','alcohol': 'snacks_drinks','crossroad': 'snacks_drinks','bakery': 'snacks_drinks','popcorn': 'snacks_drinks',
'mister_donut': 'snacks_drinks','chocolate': 'snacks_drinks','dessert': 'snacks_drinks','cassava_cake': 'snacks_drinks',
'sm_søde': 'snacks_drinks','kager': 'snacks_drinks',
# ======================
# GROCERIES
# ======================
'sm_supermarket': 'groceries','nccc_supermarket': 'groceries','robinson_supermarket': 'groceries','drugman_supermarket': 'groceries',
'supermarket': 'groceries','supermarket_taytay': 'groceries','street_store': 'groceries','unitop': 'groceries','market': 'groceries',
'shopee_supermarket': 'groceries','vegetables': 'groceries','coconut': 'groceries','eggs': 'groceries','rice': 'groceries',
'water': 'groceries','vand': 'groceries','honey': 'groceries','milkpawder': 'groceries','banana': 'groceries','mango': 'groceries',
'pineapple': 'groceries','fruit': 'groceries','fruits': 'groceries','frugt_market': 'groceries','market_fruit': 'groceries',
'cashew_nuts': 'groceries','eggplant': 'groceries','cassava': 'groceries','chicken': 'groceries','pork': 'groceries','fish': 'groceries',
'sardines': 'groceries','fish_tuna': 'groceries','fish_crab': 'groceries','shrimp': 'groceries','liempo': 'groceries','bananas': 'groceries',
'saomai_ivy': 'groceries','squash': 'groceries','bagoong': 'groceries','taho': 'groceries','cocos': 'groceries','sinigang': 'groceries',
'food': 'groceries','sugar': 'groceries','oatmeal': 'groceries','eggplantpineapple': 'groceries','street_store_baryo': 'groceries',
'coconut_oil': 'groceries','ice': 'groceries','shopee_milk': 'groceries',
# ======================
# SHOPPING/DRUGSTORE (NON-FOOD)
# ======================
'iherb': 'drugstore','listerine': 'drugstore','aloevera': 'drugstore','masks': 'drugstore','drugstore': 'drugstore','plaster': 'drugstore',
'shopee': 'shopping','amazon_horusx': 'shopping','mr_diy': 'shopping','miniso': 'shopping','phone': 'shopping','tablet_ivy': 'shopping',
'gadgets': 'shopping','speaker': 'shopping','shaver': 'shopping','sd_kort_256gb': 'shopping','bookstore': 'shopping','clothes': 'shopping',
'slippers': 'shopping','souvenir': 'shopping','hm_clothing': 'shopping','jakke_ivy': 'shopping','adidas_sko': 'shopping','bukser_ivy': 'shopping',
'levis_tøj': 'shopping','levis_tøj_ivy': 'shopping','jeans_ivy': 'shopping','smykker_sølv': 'shopping','kuffert': 'shopping','shopee_router': 'shopping',
'shopee_fans': 'shopping','aquaflask': 'shopping','adapters': 'shopping','home_wifi__powerbank': 'shopping','shopee_antenna_cable': 'shopping',
'antenna': 'shopping','store_taytay': 'shopping','shopee_books': 'shopping','bag_ivy': 'shopping','nails_ivy': 'shopping','mcbeth_ivy': 'shopping',
'shorts_hoodie': 'shopping','bible_book': 'shopping','orbkey': 'shopping','fan_ivy': 'shopping','2_bher_ivy': 'shopping','flashlight': 'shopping',
'ring_ivy': 'shopping','tshirt_robinson': 'shopping','usb': 'shopping','shoe_repair': 'shopping','shopee_dresses': 'shopping','nails_emmalisa': 'shopping',
'shoes_ivy': 'shopping','shopee_kitchenware': 'shopping','pictures': 'shopping','slippers_baby': 'shopping','ivy_underbukser': 'shopping',
'tempered_glass': 'shopping','nails_ivy': 'shopping','rejuvenating_set': 'shopping','boxers_marcus': 'shopping','belt_ivy': 'shopping',
'slippers_ivy': 'shopping','shopee_shaver': 'shopping','id_pictures': 'shopping','security_glasses': 'shopping','hård_spænde': 'shopping',
'scarf_ivy': 'shopping','gift_bag': 'shopping','wetwipes': 'shopping','napkin': 'shopping','soap': 'shopping','detergent_powder': 'shopping',
'klippe_hår': 'shopping','klippe_hårdt': 'shopping','blade': 'shopping','clipclaps__kuglepenne': 'shopping','underbukser_ivy': 'shopping',
'book_store': 'shopping','gift_marcus': 'shopping','shopee_gadgets': 'shopping','shopee_nails': 'shopping','shopping': 'shopping','hm_marcus': 'shopping',
'hm_ivy': 'shopping',
# ======================
# HEALTHCARE
# ======================
'dentist_marcusivy': 'healthcare','dentist_ivy': 'healthcare','medical_expences': 'healthcare','dermatologi_clinic': 'healthcare',
# ======================
# TRANSPORT
# ======================
'bike': 'transport','benzin': 'transport','gasoline': 'transport','tricicle': 'transport',
# ======================
# UTILITIES & FEES
# ======================
'electricity': 'housing_utilities','gas': 'housing_utilities','withdraw_fee': 'fees','gcash_fee': 'fees','prøvelsesattest': 'fees',
'visa_appointment': 'fees','insurance_shenguen': 'fees','freezer_rent': 'housing_utilities','criminal_record_ivy': 'fees',
'barangay_residency_certificate': 'fees','toilet': 'fees',
# ======================
# SUBSCRIPTIONS
# ======================
'gym': 'subscriptions','phone_warranty': 'subscriptions','visa': 'subscriptions','netflix': 'subscriptions','curiositystream': 'entertainment',
'visa_print_shop': 'subscriptions',
# ======================
# MOBILE / INTERNET
# ======================
'load_dito_sim': 'mobile_data','load_tnt_sim': 'mobile_data','piso_wifi': 'mobile_data','phebe_load': 'mobile_data',
# ======================
# FAMILY & DONATIONS
# ======================
'donation_barangay': 'donations','church': 'donations','gcash_til_ivy': 'donations','irene_laundry': 'family',
# ======================
# CONSTRUCTION
# ======================
'sand': 'construction','cement': 'construction','rebars': 'construction','alambre': 'construction','worker': 'construction',
'workers': 'construction','worker_jaime': 'construction','worker_ludito': 'construction','worker_pido': 'construction',
'rebars__plywood': 'construction','400kg_cement': 'construction','shovel__gas_11kg': 'construction','worker_abel': 'construction',
'chairs': 'construction','merchandising_taytay': 'construction','coco_lumber': 'construction','merchandising': 'construction',
'gravel': 'construction','shopee_gas_stove': 'construction','leafroof_abel': 'construction','plywood': 'construction',
'nails': 'construction','molder': 'construction','tatay_sander': 'construction','mirror__1l_bernice': 'construction',
'gloves': 'construction','shopee_electric_cable': 'construction',
# ======================
# Agriculture
# ======================
'pigfood': 'pet_food','chicken_food': 'pet_food','fiske_bid': 'pet_food',
# ======================
# Entertainment
# ======================
'cinema': 'entertainment','shooting_range': 'entertainment','museum': 'entertainment','arcade': 'entertainment',
'fort_santiago': 'entertainment',
}
# Apply mapping, keep original if not in mapping

tidy['detail_grouped'] = tidy['detail'].map(mapping)

tidy['detail_grouped'] = tidy['detail_grouped'].fillna(tidy['category']
)

tidy.loc[tidy["category"] == "transport", "detail"] = "transport"
tidy.loc[tidy["category"] == "housing_utilities", "detail"] = "housing_utilities"

In [362]:
counts = tidy["detail_grouped"].value_counts(dropna=True)  # dropna=True skips NaNs

print(counts)

detail_grouped
groceries            384
restaurants          205
snacks_drinks        191
shopping             133
transport             93
construction          57
family                57
housing_utilities     41
subscriptions         28
drugstore             25
fees                  24
mobile_data           16
pet_food              15
entertainment         12
donations              5
healthcare             4
Name: count, dtype: int64

In [363]:
tidy[
    (tidy["detail_grouped"] == "groceries") &
    (tidy["category"] == "other_things")
]

           date  amount        detail      category detail_grouped
1872 2025-02-20  2808.0        unitop  other_things      groceries
1941 2025-04-02  1202.0        unitop  other_things      groceries
2014 2025-05-12  1814.0        unitop  other_things      groceries
2095 2025-06-11  1579.0        unitop  other_things      groceries
2104 2025-06-12  1390.0        unitop  other_things      groceries
2342 2025-08-23    40.0  street_store  other_things      groceries

There is an error here; "street_store", should belong to the "food" category.
Unitop is mostly a merchandising store, but also serves as a supermarket. So the category of "other_things" is correct, however the ""detail_grouped" is wrong wich is due to the prior input of unitop in the food section.

In [364]:
tidy.loc[2342, "category"] = "food"

In [365]:
tidy[
    (tidy["detail_grouped"] == "groceries") &
    (tidy["category"] == "food")
]

           date  amount            detail category detail_grouped
3    2025-03-01  1485.0    sm_supermarket     food      groceries
5    2025-03-01    45.0            unitop     food      groceries
6    2025-03-02    20.0              vand     food      groceries
8    2025-03-03  1892.0  nccc_supermarket     food      groceries
12   2025-03-06   800.0    sm_supermarket     food      groceries
...         ...     ...               ...      ...            ...
850  2026-01-14   377.0       shopee_milk     food      groceries
851  2026-01-14   369.0    sm_supermarket     food      groceries
852  2026-01-15   470.0    sm_supermarket     food      groceries
853  2026-01-15   250.0             water     food      groceries
2342 2025-08-23    40.0      street_store     food      groceries

[363 rows x 5 columns]

In [366]:
#Change the "detail_group" of unitop
tidy.loc[5, "detail"] = "unitop_supermarket"

mapping.update({'unitop': 'shopping'})

tidy.loc[
    tidy['detail'] == 'unitop',
    'detail_grouped'
] = 'shopping'

In [367]:
tidy[
    (tidy["detail_grouped"] == "groceries") &
    (tidy["category"] == "other_things")
]

Empty DataFrame
Columns: [date, amount, detail, category, detail_grouped]
Index: []

Add 2 columns named expense_type and recurrence with capex/opex, and recurring/one_off

In [368]:
capex_keys = {
'amazon_horusx': 'shopping','mr_diy': 'shopping','phone': 'shopping','tablet_ivy': 'shopping','gadgets': 'shopping','speaker': 'shopping','shaver': 'shopping',
'sd_kort_256gb': 'shopping','bookstore': 'shopping','clothes': 'shopping','slippers': 'shopping','hm_clothing': 'shopping','jakke_ivy': 'shopping',
'adidas_sko': 'shopping','bukser_ivy': 'shopping','levis_tøj': 'shopping','levis_tøj_ivy': 'shopping','jeans_ivy': 'shopping','smykker_sølv': 'shopping',
'kuffert': 'shopping','shopee_router': 'shopping','shopee_fans': 'shopping','aquaflask': 'shopping','adapters': 'shopping','home_wifi__powerbank': 'shopping',
'shopee_antenna_cable': 'shopping','antenna': 'shopping','shopee_books': 'shopping','bag_ivy': 'shopping','mcbeth_ivy': 'shopping','shorts_hoodie': 'shopping',
'bible_book': 'shopping','orbkey': 'shopping','fan_ivy': 'shopping','2_bher_ivy': 'shopping','flashlight': 'shopping','ring_ivy': 'shopping','tshirt_robinson': 'shopping',
'usb': 'shopping','shopee_dresses': 'shopping','shoes_ivy': 'shopping','shopee_kitchenware': 'shopping','pictures': 'shopping','slippers_baby': 'shopping',
'ivy_underbukser': 'shopping','tempered_glass': 'shopping','nails_ivy': 'shopping','rejuvenating_set': 'shopping','boxers_marcus': 'shopping','belt_ivy': 'shopping',
'slippers_ivy': 'shopping','shopee_shaver': 'shopping','id_pictures': 'shopping','security_glasses': 'shopping','hård_spænde': 'shopping','scarf_ivy': 'shopping',
'gift_bag': 'shopping','clipclaps__kuglepenne': 'shopping','underbukser_ivy': 'shopping','book_store': 'shopping','gift_marcus': 'shopping','shopee_gadgets': 'shopping',
'hm_marcus': 'shopping','hm_ivy': 'shopping',
}

tidy['expense_type'] = 'operating'

tidy.loc[tidy['detail'].isin(capex_keys), 'expense_type'] = 'capital'

tidy.loc[tidy['detail_grouped'] == 'construction', 'expense_type'] = 'construction'

In [369]:
one_offs = {
'amazon_horusx': 'shopping','mr_diy': 'shopping','phone': 'shopping','tablet_ivy': 'shopping','gadgets': 'shopping','speaker': 'shopping','shaver': 'shopping',
'sd_kort_256gb': 'shopping','bookstore': 'shopping','clothes': 'shopping','slippers': 'shopping','hm_clothing': 'shopping','jakke_ivy': 'shopping','adidas_sko': 'shopping',
'bukser_ivy': 'shopping','levis_tøj': 'shopping','levis_tøj_ivy': 'shopping','jeans_ivy': 'shopping','smykker_sølv': 'shopping','kuffert': 'shopping',
'shopee_router': 'shopping','shopee_fans': 'shopping','aquaflask': 'shopping','adapters': 'shopping','home_wifi__powerbank': 'shopping','shopee_antenna_cable': 'shopping',
'antenna': 'shopping','shopee_books': 'shopping','bag_ivy': 'shopping','mcbeth_ivy': 'shopping','shorts_hoodie': 'shopping','bible_book': 'shopping',
'orbkey': 'shopping','fan_ivy': 'shopping','2_bher_ivy': 'shopping','flashlight': 'shopping','ring_ivy': 'shopping','tshirt_robinson': 'shopping',
'usb': 'shopping','shopee_dresses': 'shopping','shoes_ivy': 'shopping','shopee_kitchenware': 'shopping','pictures': 'shopping','slippers_baby': 'shopping',
'ivy_underbukser': 'shopping','tempered_glass': 'shopping','nails_ivy': 'shopping','rejuvenating_set': 'shopping','boxers_marcus': 'shopping','belt_ivy': 'shopping',
'slippers_ivy': 'shopping','shopee_shaver': 'shopping','id_pictures': 'shopping','security_glasses': 'shopping','hård_spænde': 'shopping','scarf_ivy': 'shopping',
'gift_bag': 'shopping','clipclaps__kuglepenne': 'shopping','underbukser_ivy': 'shopping','book_store': 'shopping','gift_marcus': 'shopping','shopee_gadgets': 'shopping',
'hm_marcus': 'shopping','hm_ivy': 'shopping',

'donation_barangay': 'donations','church': 'donations',

'dentist_marcusivy': 'healthcare','dentist_ivy': 'healthcare','medical_expences': 'healthcare','dermatologi_clinic': 'healthcare',

'prøvelsesattest': 'fees','visa_appointment': 'fees','insurance_shenguen': 'fees','freezer_rent': 'housing_utilities',
'criminal_record_ivy': 'fees',
'barangay_residency_certificate': 'fees',
'visa_print_shop': 'subscriptions',
}

tidy['recurrence'] = 'recurring'

tidy.loc[tidy["detail"].isin(one_offs), "recurrence"] = "one_off"

tidy.loc[tidy['detail_grouped'] == 'construction', 'recurrence'] = 'construction'

In [370]:
tidy.groupby('expense_type')['amount'].sum()

expense_type
capital         223460.0
construction    117764.0
operating       651427.0
Name: amount, dtype: float64

In [371]:
tidy.groupby('recurrence')['amount'].sum()

recurrence
construction    117764.0
one_off         269740.0
recurring       605147.0
Name: amount, dtype: float64

In [372]:
shopping_type = {

#Books
'book_store': 'books','bible_book': 'books','shopee_books': 'books','bookstore': 'books',
'gift_marcus': 'shopping',
#Gadgets and Accessories
'shopee_gadgets': 'gadgets_accessories','phone': 'gadgets_accessories','tablet_ivy': 'gadgets_accessories','gadgets': 'gadgets_accessories','speaker': 'gadgets_accessories',
'shaver': 'gadgets','sd_kort_256gb': 'gadgets_accessories','shopee_shaver': 'gadgets_accessories','usb': 'gadgets_accessories','fan_ivy': 'gadgets_accessories',
'flashlight': 'gadgets_accessories','adapters': 'gadgets_accessories','home_wifi__powerbank': 'gadgets_accessories','shopee_router': 'gadgets_accessories',
'shopee_fans': 'gadgets_accessories','shopee_antenna_cable': 'gadgets_accessories','antenna': 'gadgets_accessories','tempered_glass': 'gadgets_accessories',
#Clothing
'shopping': 'shopping','clipclaps__kuglepenne': 'clothing','hm_marcus': 'clothing','hm_ivy': 'clothing','underbukser_ivy': 'clothing','hård_spænde': 'clothing',
'scarf_ivy': 'clothing','boxers_marcus': 'clothing','belt_ivy': 'clothing','slippers_baby': 'clothing','ivy_underbukser': 'clothing','shopee_dresses': 'clothing',
'slippers_ivy': 'clothing','clothes': 'clothing','slippers': 'clothing','tshirt_robinson': 'clothing','2_bher_ivy': 'clothing','mcbeth_ivy': 'clothing',
'bag_ivy': 'clothing','shoes_ivy': 'clothing','shorts_hoodie': 'clothing','shoe_repair': 'clothing','hm_clothing': 'clothing','jakke_ivy': 'clothing',
'adidas_sko': 'clothing','bukser_ivy': 'clothing','levis_tøj': 'clothing','levis_tøj_ivy': 'clothing','jeans_ivy': 'clothing',
#Personal Care
'shopee_nails': 'personal_care','nails_emmalisa': 'personal_care','nails_ivy': 'personal_care','rejuvenating_set': 'personal_care','miniso': 'personal_care',
'nails_ivy': 'personal_care','klippe_hår': 'personal_care','klippe_hårdt': 'personal_care','blade': 'personal_care','iherb': 'personal_care',
# Jewelry / Gifts
'orbkey': 'jewelry','ring_ivy': 'jewelry','smykker_sølv': 'jewelry','gift_marcus': 'gifts','souvenir': 'gifts',
# Household / Utility
'wetwipes': 'household','napkin': 'household','soap': 'household','detergent_powder': 'household','kuffert': 'household','shopee': 'household','amazon_horusx': 'household',
'aquaflask': 'household','pictures': 'household','mr_diy': 'household','security_glasses': 'household','shopee_kitchenware': 'household','store_taytay': 'household',
'id_pictures': 'household',
}

# Map the dictionary to create a new column
tidy['shopping_type'] = tidy['detail'].map(shopping_type)

# Optionally, fill items not in the dictionary with NaN
tidy['shopping_type'] = tidy['shopping_type'].fillna(np.nan)

In [373]:
tidy.to_csv("tidy_spending3.csv", index=False)

“I transformed raw transaction data into a multi-level expense model, separated operating vs capital spending, and visualized lifestyle inflation over time.”

In [374]:

#filtered = tidy[tidy["detail_grouped"] == "other_things"]

In [375]:
counts = tidy["detail"].value_counts(dropna=True)  # dropna=True skips NaNs

print(counts)

detail
street_store                 93
bakery                       83
transport                    83
mcdonalds                    50
sm_supermarket               47
                             ..
load_irene                    1
irene                         1
vinegar                       1
gravel                        1
shopee_electricity_things     1
Name: count, Length: 273, dtype: int64

In [376]:
tidy[tidy["detail"].isna()]

Empty DataFrame
Columns: [date, amount, detail, category, detail_grouped, expense_type, recurrence, shopping_type]
Index: []